FROM registry.access.redhat.com/ubi10/python-312-minimal:1789550764

USER 0

RUN mkdir -p /licenses
COPY LICENSE /licenses

RUN microdnf install -y cargo libffi-devel openssl-devel python3.12-devel

RUN mkdir app
WORKDIR /app

USER 1001

COPY --chown=1001:0 requirements.txt requirements-build.txt pyproject.toml ./
COPY --chown=1001:0 src src
COPY --chown=1001:0 README.md .

RUN pip install -r requirements.txt && \
    pip install .

LABEL url="https://www.redhat.com"
LABEL name="satellite/foreman-mcp-server-rhel10" \
      description="A MCP server for Satellite" \
      summary="A MCP server for Satellite" \
      cpe="cpe:/a:redhat:satellite:6.20::el10"
LABEL com.redhat.component="satellite/foreman-mcp-server-rhel10" \
      io.k8s.display-name="Satellite MCP Server" \
      io.k8s.description="This adds the satellite/foreman-mcp-server-rhel10 image to the Red Hat container registry. To pull this container image, run the following command: podman pull registry.stage.redhat.io/satellite/foreman-mcp-server-rhel10" \
      io.openshift.tags="satellite mcp"

EXPOSE 8080/tcp
ENV HOST=0.0.0.0

ENTRYPOINT ["python", "-m", "foreman_mcp_server"]
