name: Build UBI images

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'tests/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'Containerfile.ubi9'
      - 'Containerfile.ubi10'
      - '.github/workflows/container.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'Containerfile.ubi9'
      - 'Containerfile.ubi10'
      - '.github/workflows/container.yml'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.release }} image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - release: UBI 9
          image: ubi9
          containerfile: Containerfile.ubi9
        - release: UBI 10
          image: ubi10
          containerfile: Containerfile.ubi10

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: foreman-mcp-server-${{ matrix.image }}
        tags: ${{ github.sha }}
        containerfiles: |
          ./${{ matrix.containerfile }}
