name: "Validate renovate.json config file"

on:
  push:
    paths:
      - '.renovaterc.json'
  pull_request:
    paths:
      - '.renovaterc.json'
   
jobs:
  renovate-config-file-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: konflux-ci/renovate-config-validator-action@main
        with:
          config_file: .renovaterc.json
